// Comentarios Actions
export const GET_COMMENT_LIST_SUCCESS = 'GET_COMMENT_LIST_SUCCESS';
export const GET_COMMENT_LIST_FAIL = 'GET_COMMENT_LIST_FAIL';

export const GET_COMMENT_LIST_BY_USER_SUCCESS = 'GET_COMMENT_LIST_BY_USER_SUCCESS';
export const GET_COMMENT_LIST_BY_USER_FAIL = 'GET_COMMENT_LIST_BY_USER_FAIL';

export const SEARCH_COMMENT_SUCCESS = 'SEARCH_COMMENT_SUCCESS';
export const SEARCH_COMMENT_FAIL = 'SEARCH_COMMENT_FAIL';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL';

export const UPDATE_COMMENTS = 'UPDATE_COMMENTS'
